/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package review.form;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author neil
 */
public class SinhVienForm extends javax.swing.JFrame {

    /**
     * Creates new form SinhVienForm
     */
    public SinhVienForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textname1 = new javax.swing.JLabel();
        textname = new javax.swing.JTextField();
        textname2 = new javax.swing.JLabel();
        textbirth = new javax.swing.JTextField();
        textname3 = new javax.swing.JLabel();
        textlocation = new javax.swing.JTextField();
        textname5 = new javax.swing.JLabel();
        selectMale = new javax.swing.JComboBox<>();
        textname4 = new javax.swing.JLabel();
        textcode = new javax.swing.JTextField();
        textname7 = new javax.swing.JLabel();
        textmail = new javax.swing.JTextField();
        textname6 = new javax.swing.JLabel();
        textscore = new javax.swing.JTextField();
        read = new javax.swing.JButton();
        add = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        modelSt = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textname1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textname1.setText("Ho va ten");

        textname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnameActionPerformed(evt);
            }
        });

        textname2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textname2.setText("Ngay sinh");

        textbirth.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textbirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textbirthActionPerformed(evt);
            }
        });

        textname3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textname3.setText("Dia chi");

        textlocation.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textlocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textlocationActionPerformed(evt);
            }
        });

        textname5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textname5.setText("Gioi tinh");

        selectMale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nu", "Khong xac dinh" }));
        selectMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectMaleActionPerformed(evt);
            }
        });

        textname4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textname4.setText("MSV");

        textcode.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcodeActionPerformed(evt);
            }
        });

        textname7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textname7.setText("Email");

        textmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textmailActionPerformed(evt);
            }
        });

        textname6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textname6.setText("Diem TK");

        textscore.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textscore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textscoreActionPerformed(evt);
            }
        });

        read.setText("Xem");
        read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readActionPerformed(evt);
            }
        });

        add.setText("Them");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        save.setText("Luu");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        modelSt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ho ten", "Ngay sinh", "Dia chi", "Gioi tinh", "MaSV", "Email", "DiemTK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(modelSt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textname6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textscore, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textname4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textcode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textname7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(464, 464, 464)
                                .addComponent(read, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textname1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(textname2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textname3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(textname5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(selectMale, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textname2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textname1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textname, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textname3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textname5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(selectMale, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textname7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textname4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textcode, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textname6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textscore, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(read, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textlocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textlocationActionPerformed

    private void textmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textmailActionPerformed

    private void textnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnameActionPerformed

    private void textbirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textbirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textbirthActionPerformed

    private void selectMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectMaleActionPerformed

    private void textcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcodeActionPerformed

    private void textscoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textscoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textscoreActionPerformed

    private SinhVien getDataForm() {
        SinhVien data = new SinhVien();
        data.hoten = textname.getText();
        data.gioitinh = selectMale.getSelectedItem().toString();
        data.ngaysinh = textbirth.getText();
        data.diachi = textlocation.getText();
        data.masv = textcode.getText();
        data.email = textmail.getText();
        if (!textscore.getText().isEmpty()) {
            data.diemtk = Double.parseDouble(textscore.getText());
        }
        return data;
    }

    private void readActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readActionPerformed
        // TODO add your handling code here:
        String[] coloumns = {"Ho ten", "Dia chi", "Ngay sinh", "Gioi tinh", "MaSV", "Email", "DiemTK"};
        DefaultTableModel tableSt = new DefaultTableModel(coloumns, 0);
        modelSt.setModel(tableSt);
        try (BufferedReader br = new BufferedReader(new FileReader("/home/neil/Downloads/sinhvien.dat"))) {
            String line;
            ArrayList<SinhVien> arr = new ArrayList<>();
            while ((line = br.readLine()) != null) {
                String[] sv = line.split("\\$");
                SinhVien x = new SinhVien();
                x.hoten = sv[0];
                x.ngaysinh = sv[1];
                x.diachi = sv[2];
                x.gioitinh = sv[3];
                x.masv = sv[4];
                x.email = sv[5];
                x.diemtk = Double.parseDouble(sv[6]);
                arr.add(x);
            }
            for(SinhVien x: arr) { 
                Object[] rowData = {x.hoten, x.diachi, x.ngaysinh, x.gioitinh, x.masv, x.email, x.diemtk}; 
                tableSt.addRow(rowData);
            }
        } catch (NumberFormatException err) {
            err.printStackTrace();
            JOptionPane.showMessageDialog(null, "Loi dinh dang so", "Loi", JOptionPane.ERROR_MESSAGE);
        } catch (Exception err) {
            err.printStackTrace();
            JOptionPane.showMessageDialog(null, "Loi khong mong muon", "Loi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_readActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        try {
            SinhVien data = getDataForm();
            data.hienThongtin();
        } catch (NumberFormatException err) {
            err.printStackTrace();
            JOptionPane.showMessageDialog(null, "Loi dinh dang so", "Loi", JOptionPane.ERROR_MESSAGE);
        } catch (Exception err) {
            err.printStackTrace();
            JOptionPane.showMessageDialog(null, "Loi khong mong muon", "Loi", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_addActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:datdat
        ArrayList<SinhVien> sv = new ArrayList<>();
        File file = new File("/home/neil/Downloads/sinhvien.dat");
        try (PrintWriter out = new PrintWriter(new FileWriter(file, true))) {
            SinhVien data = getDataForm();
            sv.add(data);
            for (SinhVien x : sv) {
                out.println(x.hoten + "$" + x.ngaysinh + "$" + x.diachi + "$" + x.gioitinh + "$" + x.masv + "$" + x.email + "$" + x.diemtk);
            }
            out.close();
            JOptionPane.showMessageDialog(null, "Thanh Cong", "Thanh cong", JOptionPane.DEFAULT_OPTION);
        } catch (Exception err) {
            err.printStackTrace();
            JOptionPane.showMessageDialog(null, "Loi khong mong muon", "Loi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinhVienForm().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable modelSt;
    private javax.swing.JButton read;
    private javax.swing.JButton save;
    private javax.swing.JComboBox<String> selectMale;
    private javax.swing.JTextField textbirth;
    private javax.swing.JTextField textcode;
    private javax.swing.JTextField textlocation;
    private javax.swing.JTextField textmail;
    private javax.swing.JTextField textname;
    private javax.swing.JLabel textname1;
    private javax.swing.JLabel textname2;
    private javax.swing.JLabel textname3;
    private javax.swing.JLabel textname4;
    private javax.swing.JLabel textname5;
    private javax.swing.JLabel textname6;
    private javax.swing.JLabel textname7;
    private javax.swing.JTextField textscore;
    // End of variables declaration//GEN-END:variables
}
